package examen.fapte_bune.domain;

public enum Oras {
        ALBA_IULIA,
        ARAD,
        BACAU,
        BAIA_MARE,
        BISTRITA,
        BOTOSANI,
        BRAILA,
        BRASOV,
        BUZAU,
        BUCURESTI,
        CALARASI,
        CLUJ_NAPOCA,
        CONSTANTA,
        CRAIOVA,
        DEVA,
        FAGARAS,
        FOCSANI,
        GALATI,
        GIURGIU,
        IASI,
        ORADEA,
        PETROSANI,
        PITESTI,
        PLOIESTI,
        RAMNICU_VALCEA,
        RESITA,
        SATU_MARE,
        SIBIU,
        SUCEAVA,
        TIMISOARA,
        TARGU_MURES
}
